[build]
builder = "nixpacks"

[build.nixpacksConfig]
packages = ["nodejs", "python3", "curl", "bash"]

[build.nixpacksConfig.phases.build]
cmds = [
    "curl -LsSf https://astral.sh/uv/install.sh | sh",
    "export PATH=\"$HOME/.cargo/bin:$PATH\"",
    "echo 'export PATH=\"$HOME/.cargo/bin:$PATH\"' >> $HOME/.profile"
]

[deploy]
startCommand = "bash -l -c 'pnpm run start'"